CREATE TABLE IF NOT EXISTS tv_show
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(128),
    year            INTEGER,
    dropped         BOOLEAN,
    forgettability  DECIMAL(4, 2),
    expectations_id INT REFERENCES expectations (id),
    genres_id       INT REFERENCES genre (id),
    mood_id         INT REFERENCES mood (id),
    format_id INT REFERENCES format(id)

);

CREATE TABLE IF NOT EXISTS mood
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    state         VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS genre
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    name          VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS expectations
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    state         VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS format
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    name          VARCHAR(50)
)
