CREATE TABLE IF NOT EXISTS tv_show
(
    -- general info
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(256) NOT NULL,
    year                INT          NOT NULL,
    title_in_latin      VARCHAR(256),
    setting             VARCHAR(32),
    format_id           INT REFERENCES format (id),
    post_insight_id     INT REFERENCES post_insight (id),
    -- impressions
    extended_opinion    TEXT,
    moral_understanding TEXT,
    finished            BOOLEAN,
    expectations_id     INT REFERENCES expectations (id),
    genres_id           INT REFERENCES genre (id),
    mood_id             INT REFERENCES mood (id),
    strengths_id        INT REFERENCES strengths (id),
    annoyances_id       INT REFERENCES annoyances (id),
    impressions_id      INT REFERENCES impressions (id),
    visual_rate         SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    dialogues_rate      SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    characters_rate     SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    story_rate          SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    atmosphere_rate     SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    moral_depth_rate    SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    originality_rate    SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10)
);


CREATE TABLE IF NOT EXISTS post_insight
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rewatched           BOOLEAN,
    forgettability      DECIMAL(4, 2) CHECK ( forgettability BETWEEN 0.0 AND 100.0),
    -- OG fields
    extended_opinion    TEXT,
    moral_understanding TEXT,
    finished            BOOLEAN,
    expectations_id     INT REFERENCES expectations (id),
    genres_id           INT REFERENCES genre (id),
    mood_id             INT REFERENCES mood (id),
    strengths_id        INT REFERENCES strengths (id),
    annoyances_id       INT REFERENCES annoyances (id),
    impressions_id      INT REFERENCES impressions (id),
    visual_rate         SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    dialogues_rate      SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    characters_rate     SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    story_rate          SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    atmosphere_rate     SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    moral_depth_rate    SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10),
    originality_rate    SMALLINT CHECK ( dialogues_rate BETWEEN 1 AND 10)
);


CREATE TABLE IF NOT EXISTS mood
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    state         VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS genre
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    name                 VARCHAR(50),
    displayed_by_default BOOLEAN
);

CREATE TABLE IF NOT EXISTS expectations
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    state                VARCHAR(50),
    displayed_by_default BOOLEAN
);

CREATE TABLE IF NOT EXISTS impressions
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    state                VARCHAR(50),
    order_number                INT,
    displayed_by_default BOOLEAN
);


CREATE TABLE IF NOT EXISTS format
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(2),
    name          VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS strengths
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    name                 VARCHAR(50),
    displayed_by_default BOOLEAN
);

CREATE TABLE IF NOT EXISTS annoyances
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    name                 VARCHAR(50),
    displayed_by_default BOOLEAN
);

CREATE TABLE IF NOT EXISTS pacing
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beginning SMALLINT CHECK ( beginning BETWEEN 1 AND 10),
    ending    SMALLINT CHECK ( ending BETWEEN 1 AND 10),
    middle    SMALLINT CHECK ( middle BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS setting
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code        VARCHAR(2),
    name                 VARCHAR(50),
    displayed_by_default BOOLEAN
);
