export type TvShow = {
id: number,
title: string,
year: number,
title_in_latin: string | null,
country: string | null,
setting: string | null,
format_id: number | null,
post_insight_id: number | null,
user_account_id: number | null,
extended_opinion: string | null,
moral_understanding: string | null,
finished: number | null,
expectations_id: number | null,
genres_id: number | null,
mood_id: number | null,
strengths_id: number | null,
annoyances_id: number | null,
impressions_id: number | null,
visual_rate: number | null,
dialogues_rate: number | null,
characters_rate: number | null,
story_rate: number | null,
atmosphere_rate: number | null,
moral_depth_rate: number | null,
originality_rate: number | null,
}
