// Code generated by sqlode. DO NOT EDIT.

import gleam/option.{type Option}

pub type Author {
  Author(id: Int, name: String, bio: Option(String), created_at: String)
}

pub type GetAuthorRow {
  GetAuthorRow(id: Int, name: String, bio: Option(String))
}

pub type ListAuthorsRow {
  ListAuthorsRow(id: Int, name: String)
}
