// Code generated by sqlode. DO NOT EDIT.

import gleam/option.{type Option}

pub type Mood {
  Mood(
    id: Int,
    language_code: String,
    state: String,
    category: String,
    displayed_by_default: Option(Int),
  )
}

pub type Genre {
  Genre(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Expectation {
  Expectation(
    id: Int,
    language_code: String,
    state: String,
    displayed_by_default: Option(Int),
  )
}

pub type Impression {
  Impression(
    id: Int,
    language_code: String,
    state: String,
    order_number: Int,
    displayed_by_default: Option(Int),
  )
}

pub type Format {
  Format(id: Int, language_code: String, name: String)
}

pub type Strength {
  Strength(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Annoyance {
  Annoyance(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Pacing {
  Pacing(
    id: Int,
    beginning: Option(Int),
    ending: Option(Int),
    middle: Option(Int),
  )
}

pub type Setting {
  Setting(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type PostInsight {
  PostInsight(
    id: Int,
    rewatched: Option(Int),
    forgettability: Option(Float),
    extended_opinion: Option(String),
    moral_understanding: Option(String),
    finished: Option(Int),
    expectations_id: Option(Int),
    genres_id: Option(Int),
    mood_id: Option(Int),
    strengths_id: Option(Int),
    annoyances_id: Option(Int),
    impressions_id: Option(Int),
    visual_rate: Option(Int),
    dialogues_rate: Option(Int),
    characters_rate: Option(Int),
    story_rate: Option(Int),
    atmosphere_rate: Option(Int),
    moral_depth_rate: Option(Int),
    originality_rate: Option(Int),
  )
}

pub type UserAccount {
  UserAccount(
    id: Int,
    email: String,
    custom_strength_id: Option(Int),
    custom_annoyance_id: Option(Int),
  )
}

pub type TvShow {
  TvShow(
    id: Int,
    title: String,
    year: Int,
    title_in_latin: Option(String),
    country: Option(String),
    setting: Option(String),
    format_id: Option(Int),
    post_insight_id: Option(Int),
    user_account_id: Option(Int),
    extended_opinion: Option(String),
    moral_understanding: Option(String),
    finished: Option(Int),
    expectations_id: Option(Int),
    genres_id: Option(Int),
    mood_id: Option(Int),
    strengths_id: Option(Int),
    annoyances_id: Option(Int),
    impressions_id: Option(Int),
    visual_rate: Option(Int),
    dialogues_rate: Option(Int),
    characters_rate: Option(Int),
    story_rate: Option(Int),
    atmosphere_rate: Option(Int),
    moral_depth_rate: Option(Int),
    originality_rate: Option(Int),
  )
}

pub type GetAllGenresByLanguageCodeRow =
  Genre

pub type GetAllShowFormatsByLanguageCodeRow =
  Format

pub type GetAllDefaultMoodByLanguageCodeRow =
  Mood

pub type GetAllDefaultExpectationsByLanguageCodeRow =
  Expectation

pub type GetAllDefaultImpressionsByLanguageCodeRow =
  Impression

pub type GetAllDefaultStrengthsByLanguageCodeRow =
  Strength

pub type GetSpecificStrengthRow =
  Strength

pub type GetSpecificAnnoyanceRow =
  Annoyance

pub type GetAllDefaultAnnoyancesByLanguageCodeRow =
  Annoyance

pub type GetAllDefaultShowSettingRow =
  Setting

pub type GetUserAccountIdByEmailRow {
  GetUserAccountIdByEmailRow(id: Int)
}
