// Code generated by sqlode. DO NOT EDIT.

import gleam/option.{type Option}

pub type Mood {
  Mood(
    id: Int,
    language_code: String,
    state: String,
    displayed_by_default: Option(Int),
  )
}

pub type Genre {
  Genre(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Expectation {
  Expectation(
    id: Int,
    language_code: String,
    state: String,
    displayed_by_default: Option(Int),
  )
}

pub type Impression {
  Impression(
    id: Int,
    language_code: String,
    state: String,
    order_number: Int,
    displayed_by_default: Option(Int),
  )
}

pub type Format {
  Format(id: Int, language_code: String, name: String)
}

pub type Strength {
  Strength(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Annoyance {
  Annoyance(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type Pacing {
  Pacing(
    id: Int,
    beginning: Option(Int),
    ending: Option(Int),
    middle: Option(Int),
  )
}

pub type Setting {
  Setting(
    id: Int,
    language_code: String,
    name: String,
    displayed_by_default: Option(Int),
  )
}

pub type PostInsight {
  PostInsight(
    id: Int,
    rewatched: Option(Int),
    forgettability: Option(Float),
    extended_opinion: Option(String),
    moral_understanding: Option(String),
    finished: Option(Int),
    visual_rate: Option(Int),
    dialogues_rate: Option(Int),
    characters_rate: Option(Int),
    story_rate: Option(Int),
    atmosphere_rate: Option(Int),
    moral_depth_rate: Option(Int),
    originality_rate: Option(Int),
  )
}

pub type UserAccount {
  UserAccount(
    id: Int,
    email: String,
    custom_strength_id: Option(Int),
    custom_annoyance_id: Option(Int),
  )
}

pub type TvShow {
  TvShow(
    id: Int,
    title: String,
    year: Int,
    title_in_latin: Option(String),
    country: Option(String),
    extended_opinion: Option(String),
    moral_understanding: Option(String),
    finished: Option(Int),
    visual_rate: Option(Int),
    dialogues_rate: Option(Int),
    characters_rate: Option(Int),
    story_rate: Option(Int),
    atmosphere_rate: Option(Int),
    moral_depth_rate: Option(Int),
    originality_rate: Option(Int),
  )
}

pub type MoodTvShowChain {
  MoodTvShowChain(id: Int, tv_show_id: Int, mood_id: Int)
}

pub type GenreTvShowChain {
  GenreTvShowChain(id: Int, tv_show_id: Int, genre_id: Int)
}

pub type ExpectationsTvShowChain {
  ExpectationsTvShowChain(id: Int, tv_show_id: Int, expectation_id: Int)
}

pub type ImpressionsTvShowChain {
  ImpressionsTvShowChain(id: Int, tv_show_id: Int, impression_id: Int)
}

pub type FormatTvShowChain {
  FormatTvShowChain(id: Int, tv_show_id: Int, format_id: Int)
}

pub type StrengthsTvShowChain {
  StrengthsTvShowChain(id: Int, user_account_id: Int, strength_id: Int)
}

pub type AnnoyancesTvShowChain {
  AnnoyancesTvShowChain(id: Int, user_account_id: Int, annoyance_id: Int)
}

pub type PacingTvShowChain {
  PacingTvShowChain(id: Int, pacing_id: Int, tv_show_id: Int)
}

pub type SettingTvShowChain {
  SettingTvShowChain(id: Int, tv_show_id: Int, setting_id: Int)
}

pub type MoodPostInsightChain {
  MoodPostInsightChain(id: Int, post_insight_id: Int, mood_id: Int)
}

pub type GenrePostInsightChain {
  GenrePostInsightChain(id: Int, post_insight_id: Int, genre_id: Int)
}

pub type ExpectationsPostInsightChain {
  ExpectationsPostInsightChain(
    id: Int,
    post_insight_id: Int,
    expectation_id: Int,
  )
}

pub type ImpressionsPostInsightChain {
  ImpressionsPostInsightChain(id: Int, post_insight_id: Int, impression_id: Int)
}

pub type FormatPostInsightChain {
  FormatPostInsightChain(id: Int, post_insight_id: Int, format_id: Int)
}

pub type StrengthsPostInsightChain {
  StrengthsPostInsightChain(id: Int, user_account_id: Int, strengthsid: Int)
}

pub type AnnoyancesPostInsightChain {
  AnnoyancesPostInsightChain(id: Int, user_account_id: Int, annoyance_id: Int)
}

pub type PacingPostInsightChain {
  PacingPostInsightChain(id: Int, pacing_id: Int, post_insight_id: Int)
}

pub type SettingPostInsightChain {
  SettingPostInsightChain(id: Int, post_insight_id: Int, setting_id: Int)
}

pub type GetAllGenresRow =
  Genre

pub type GetAllShowFormatsRow =
  Format

pub type GetAllDefaultMoodRow =
  Mood

pub type GetAllDefaultExpectationsRow =
  Expectation

pub type GetAllDefaultImpressionsRow =
  Impression

pub type GetAllDefaultStrengthsRow =
  Strength

pub type GetSpecificStrengthRow =
  Strength

pub type GetSpecificAnnoyancesRow =
  Annoyance

pub type GetAllDefaultAnnoyancesRow =
  Annoyance

pub type GetAllDefaultShowSettingRow =
  Setting

pub type GetUserAccountIdByEmailRow {
  GetUserAccountIdByEmailRow(id: Int)
}
