// Code generated by sqlode. DO NOT EDIT.

import gleam/option.{type Option}
import sqlode/runtime.{type Value}

pub type GetAuthorParams {
  GetAuthorParams(id: Int)
}

pub fn get_author_values(params: GetAuthorParams) -> List(Value) {
  [runtime.int(params.id)]
}

pub type CreateAuthorParams {
  CreateAuthorParams(author_name: String, bio: Option(String))
}

pub fn create_author_values(params: CreateAuthorParams) -> List(Value) {
  [
    runtime.string(params.author_name),
    runtime.nullable(params.bio, runtime.string),
  ]
}
