// Code generated by sqlode. DO NOT EDIT.

import sqlode/runtime.{type Value}

pub type GetAllGenresByLanguageCodeParams {
  GetAllGenresByLanguageCodeParams(language_code: String)
}

pub fn get_all_genres_by_language_code_values(
  params: GetAllGenresByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllShowFormatsByLanguageCodeParams {
  GetAllShowFormatsByLanguageCodeParams(language_code: String)
}

pub fn get_all_show_formats_by_language_code_values(
  params: GetAllShowFormatsByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllDefaultMoodByLanguageCodeParams {
  GetAllDefaultMoodByLanguageCodeParams(language_code: String)
}

pub fn get_all_default_mood_by_language_code_values(
  params: GetAllDefaultMoodByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllDefaultExpectationsByLanguageCodeParams {
  GetAllDefaultExpectationsByLanguageCodeParams(language_code: String)
}

pub fn get_all_default_expectations_by_language_code_values(
  params: GetAllDefaultExpectationsByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllDefaultImpressionsByLanguageCodeParams {
  GetAllDefaultImpressionsByLanguageCodeParams(language_code: String)
}

pub fn get_all_default_impressions_by_language_code_values(
  params: GetAllDefaultImpressionsByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllDefaultStrengthsByLanguageCodeParams {
  GetAllDefaultStrengthsByLanguageCodeParams(language_code: String)
}

pub fn get_all_default_strengths_by_language_code_values(
  params: GetAllDefaultStrengthsByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetSpecificStrengthParams {
  GetSpecificStrengthParams(name: String)
}

pub fn get_specific_strength_values(
  params: GetSpecificStrengthParams,
) -> List(Value) {
  [runtime.string(params.name)]
}

pub type GetSpecificAnnoyanceParams {
  GetSpecificAnnoyanceParams(name: String)
}

pub fn get_specific_annoyance_values(
  params: GetSpecificAnnoyanceParams,
) -> List(Value) {
  [runtime.string(params.name)]
}

pub type GetAllDefaultAnnoyancesByLanguageCodeParams {
  GetAllDefaultAnnoyancesByLanguageCodeParams(language_code: String)
}

pub fn get_all_default_annoyances_by_language_code_values(
  params: GetAllDefaultAnnoyancesByLanguageCodeParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetAllDefaultShowSettingParams {
  GetAllDefaultShowSettingParams(language_code: String)
}

pub fn get_all_default_show_setting_values(
  params: GetAllDefaultShowSettingParams,
) -> List(Value) {
  [runtime.string(params.language_code)]
}

pub type GetUserAccountIdByEmailParams {
  GetUserAccountIdByEmailParams(email: String)
}

pub fn get_user_account_id_by_email_values(
  params: GetUserAccountIdByEmailParams,
) -> List(Value) {
  [runtime.string(params.email)]
}
