// Code generated by sqlode. DO NOT EDIT.

import gleam/option.{type Option}
import sqlode/runtime.{type Value}

pub type GetSpecificStrengthParams {
  GetSpecificStrengthParams(name: String)
}

pub fn get_specific_strength_values(
  params: GetSpecificStrengthParams,
) -> List(Value) {
  [runtime.string(params.name)]
}

pub type GetSpecificAnnoyancesParams {
  GetSpecificAnnoyancesParams(name: String)
}

pub fn get_specific_annoyances_values(
  params: GetSpecificAnnoyancesParams,
) -> List(Value) {
  [runtime.string(params.name)]
}

pub type GetUserAccountIdByEmailParams {
  GetUserAccountIdByEmailParams(email: String)
}

pub fn get_user_account_id_by_email_values(
  params: GetUserAccountIdByEmailParams,
) -> List(Value) {
  [runtime.string(params.email)]
}

pub type AddTvShowParams {
  AddTvShowParams(
    title: String,
    year: Int,
    title_in_latin: Option(String),
    country: Option(String),
    setting: Option(String),
    format_id: Option(Int),
    post_insight_id: Option(Int),
    extended_opinion: Option(String),
    moral_understanding: Option(String),
    finished: Option(Int),
    expectations_id: Option(Int),
    genres_id: Option(Int),
    mood_id: Option(Int),
    user_account_id: Option(Int),
    strengths_id: Option(Int),
    annoyances_id: Option(Int),
    impressions_id: Option(Int),
    visual_rate: Option(Int),
    dialogues_rate: Option(Int),
    characters_rate: Option(Int),
    story_rate: Option(Int),
    atmosphere_rate: Option(Int),
    moral_depth_rate: Option(Int),
    originality_rate: Option(Int),
  )
}

pub fn add_tv_show_values(params: AddTvShowParams) -> List(Value) {
  [
    runtime.string(params.title),
    runtime.int(params.year),
    runtime.nullable(params.title_in_latin, runtime.string),
    runtime.nullable(params.country, runtime.string),
    runtime.nullable(params.setting, runtime.string),
    runtime.nullable(params.format_id, runtime.int),
    runtime.nullable(params.post_insight_id, runtime.int),
    runtime.nullable(params.extended_opinion, runtime.string),
    runtime.nullable(params.moral_understanding, runtime.string),
    runtime.nullable(params.finished, runtime.int),
    runtime.nullable(params.expectations_id, runtime.int),
    runtime.nullable(params.genres_id, runtime.int),
    runtime.nullable(params.mood_id, runtime.int),
    runtime.nullable(params.user_account_id, runtime.int),
    runtime.nullable(params.strengths_id, runtime.int),
    runtime.nullable(params.annoyances_id, runtime.int),
    runtime.nullable(params.impressions_id, runtime.int),
    runtime.nullable(params.visual_rate, runtime.int),
    runtime.nullable(params.dialogues_rate, runtime.int),
    runtime.nullable(params.characters_rate, runtime.int),
    runtime.nullable(params.story_rate, runtime.int),
    runtime.nullable(params.atmosphere_rate, runtime.int),
    runtime.nullable(params.moral_depth_rate, runtime.int),
    runtime.nullable(params.originality_rate, runtime.int),
  ]
}
