// Code generated by sqlode. DO NOT EDIT.

import db/models
import db/params
import db/queries
import gleam/dynamic/decode
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import pog
import sqlode/runtime

fn value_to_pog(value: runtime.Value) -> pog.Value {
  case value {
    runtime.Null -> pog.null()
    runtime.String(v) -> pog.text(v)
    runtime.Int(v) -> pog.int(v)
    runtime.Float(v) -> pog.float(v)
    runtime.Bool(v) -> pog.bool(v)
    runtime.Bytes(v) -> pog.bytea(v)
    runtime.Array(vs) -> pog.array(value_to_pog, vs)
  }
}

pub fn get_author(
  db: pog.Connection,
  p: params.GetAuthorParams,
) -> Result(Option(models.GetAuthorRow), pog.QueryError) {
  let q = queries.get_author()
  let #(sql, values) = runtime.prepare(q, p)
  let query = pog.query(sql)
  let query =
    list.fold(values, query, fn(acc, v) { pog.parameter(acc, value_to_pog(v)) })
  query
  |> pog.returning({
    use id <- decode.field(0, decode.int)
    use name <- decode.field(1, decode.string)
    use bio <- decode.field(2, decode.optional(decode.string))
    decode.success(models.GetAuthorRow(id:, name:, bio:))
  })
  |> pog.execute(db)
  |> result.map(fn(returned) {
    case returned.rows {
      [row, ..] -> Some(row)
      [] -> None
    }
  })
}

pub fn list_authors(
  db: pog.Connection,
) -> Result(List(models.ListAuthorsRow), pog.QueryError) {
  let q = queries.list_authors()
  let #(sql, _values) = runtime.prepare(q, Nil)
  pog.query(sql)
  |> pog.returning({
    use id <- decode.field(0, decode.int)
    use name <- decode.field(1, decode.string)
    decode.success(models.ListAuthorsRow(id:, name:))
  })
  |> pog.execute(db)
  |> result.map(fn(returned) { returned.rows })
}

pub fn create_author(
  db: pog.Connection,
  p: params.CreateAuthorParams,
) -> Result(Nil, pog.QueryError) {
  let q = queries.create_author()
  let #(sql, values) = runtime.prepare(q, p)
  let query = pog.query(sql)
  let query =
    list.fold(values, query, fn(acc, v) { pog.parameter(acc, value_to_pog(v)) })
  query
  |> pog.returning(decode.success(Nil))
  |> pog.execute(db)
  |> result.map(fn(_) { Nil })
}
