// Code generated by sqlode. DO NOT EDIT.
// engine: postgresql
// runtime: native

import db/models
import db/params
import gleam/dynamic/decode
import gleam/option.{type Option}
import sqlode/runtime

pub fn all() -> List(runtime.QueryInfo) {
  [
    runtime.QueryInfo(
      name: "GetAuthor",
      sql: "select id, name, bio from authors where id = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "ListAuthors",
      sql: "select id, name from authors order by name;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "CreateAuthor",
      sql: "insert into authors(name, bio) values($1, $2);",
      command: runtime.Exec,
      param_count: 2,
    ),
  ]
}

pub fn get_author() -> runtime.RawQuery(params.GetAuthorParams) {
  runtime.RawQuery(
    name: "GetAuthor",
    sql: "select id, name, bio from authors where id = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.DollarNumbered,
    encode: params.get_author_values,
    slice_info: fn(_) { [] },
  )
}

pub fn list_authors() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "ListAuthors",
    sql: "select id, name from authors order by name;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.DollarNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn create_author() -> runtime.RawQuery(params.CreateAuthorParams) {
  runtime.RawQuery(
    name: "CreateAuthor",
    sql: "insert into authors(name, bio) values(__sqlode_param_1__, __sqlode_param_2__);",
    command: runtime.Exec,
    param_count: 2,
    placeholder_style: runtime.DollarNumbered,
    encode: params.create_author_values,
    slice_info: fn(_) { [] },
  )
}

pub fn prepare_get_author(id id: Int) -> #(String, List(runtime.Value)) {
  runtime.prepare(get_author(), params.GetAuthorParams(id: id))
}

pub fn prepare_list_authors() -> #(String, List(runtime.Value)) {
  runtime.prepare(list_authors(), Nil)
}

pub fn prepare_create_author(
  author_name author_name: String,
  bio bio: Option(String),
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    create_author(),
    params.CreateAuthorParams(author_name: author_name, bio: bio),
  )
}

pub fn get_author_decoder() -> decode.Decoder(models.GetAuthorRow) {
  use id <- decode.field(0, decode.int)
  use name <- decode.field(1, decode.string)
  use bio <- decode.field(2, decode.optional(decode.string))
  decode.success(models.GetAuthorRow(id:, name:, bio:))
}

pub fn list_authors_decoder() -> decode.Decoder(models.ListAuthorsRow) {
  use id <- decode.field(0, decode.int)
  use name <- decode.field(1, decode.string)
  decode.success(models.ListAuthorsRow(id:, name:))
}
