// Code generated by sqlode. DO NOT EDIT.
// engine: sqlite
// runtime: native

import db/models
import db/params
import gleam/dynamic/decode
import gleam/option.{type Option}
import sqlode/runtime

pub fn all() -> List(runtime.QueryInfo) {
  [
    runtime.QueryInfo(
      name: "GetAllGenres",
      sql: "select* from genre;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllShowFormats",
      sql: "select* from format;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultMood",
      sql: "select* from mood where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultExpectations",
      sql: "select* from expectations where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultImpressions",
      sql: "select* from impressions where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultStrengths",
      sql: "select* from strengths where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetSpecificStrength",
      sql: "select* from strengths where name = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetSpecificAnnoyances",
      sql: "select* from annoyances where name = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultAnnoyances",
      sql: "select* from annoyances where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultShowSetting",
      sql: "select* from setting where displayed_by_default = true;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetUserAccountIdByEmail",
      sql: "select id from user_account where email = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "AddTvShow",
      sql: "",
      command: runtime.Exec,
      param_count: 0,
    ),
  ]
}

pub fn get_all_genres() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllGenres",
    sql: "select* from genre;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_show_formats() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllShowFormats",
    sql: "select* from format;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_mood() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultMood",
    sql: "select* from mood where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_expectations() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultExpectations",
    sql: "select* from expectations where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_impressions() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultImpressions",
    sql: "select* from impressions where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_strengths() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultStrengths",
    sql: "select* from strengths where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_specific_strength() -> runtime.RawQuery(
  params.GetSpecificStrengthParams,
) {
  runtime.RawQuery(
    name: "GetSpecificStrength",
    sql: "select* from strengths where name = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_specific_strength_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_specific_annoyances() -> runtime.RawQuery(
  params.GetSpecificAnnoyancesParams,
) {
  runtime.RawQuery(
    name: "GetSpecificAnnoyances",
    sql: "select* from annoyances where name = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_specific_annoyances_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_annoyances() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultAnnoyances",
    sql: "select* from annoyances where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_show_setting() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "GetAllDefaultShowSetting",
    sql: "select* from setting where displayed_by_default = true;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_user_account_id_by_email() -> runtime.RawQuery(
  params.GetUserAccountIdByEmailParams,
) {
  runtime.RawQuery(
    name: "GetUserAccountIdByEmail",
    sql: "select id from user_account where email = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_user_account_id_by_email_values,
    slice_info: fn(_) { [] },
  )
}

pub fn add_tv_show() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "AddTvShow",
    sql: "",
    command: runtime.Exec,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn prepare_get_all_genres() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_genres(), Nil)
}

pub fn prepare_get_all_show_formats() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_show_formats(), Nil)
}

pub fn prepare_get_all_default_mood() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_mood(), Nil)
}

pub fn prepare_get_all_default_expectations() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_expectations(), Nil)
}

pub fn prepare_get_all_default_impressions() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_impressions(), Nil)
}

pub fn prepare_get_all_default_strengths() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_strengths(), Nil)
}

pub fn prepare_get_specific_strength(
  name name: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_specific_strength(),
    params.GetSpecificStrengthParams(name: name),
  )
}

pub fn prepare_get_specific_annoyances(
  name name: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_specific_annoyances(),
    params.GetSpecificAnnoyancesParams(name: name),
  )
}

pub fn prepare_get_all_default_annoyances() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_annoyances(), Nil)
}

pub fn prepare_get_all_default_show_setting() -> #(String, List(runtime.Value)) {
  runtime.prepare(get_all_default_show_setting(), Nil)
}

pub fn prepare_get_user_account_id_by_email(
  email email: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_user_account_id_by_email(),
    params.GetUserAccountIdByEmailParams(email: email),
  )
}

pub fn prepare_add_tv_show() -> #(String, List(runtime.Value)) {
  runtime.prepare(add_tv_show(), Nil)
}

pub fn get_all_genres_decoder() -> decode.Decoder(models.GetAllGenresRow) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Genre(id:, language_code:, name:, displayed_by_default:))
}

pub fn get_all_show_formats_decoder() -> decode.Decoder(
  models.GetAllShowFormatsRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  decode.success(models.Format(id:, language_code:, name:))
}

pub fn get_all_default_mood_decoder() -> decode.Decoder(
  models.GetAllDefaultMoodRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Mood(id:, language_code:, state:, displayed_by_default:))
}

pub fn get_all_default_expectations_decoder() -> decode.Decoder(
  models.GetAllDefaultExpectationsRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Expectation(
    id:,
    language_code:,
    state:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_impressions_decoder() -> decode.Decoder(
  models.GetAllDefaultImpressionsRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use order_number <- decode.field(3, decode.int)
  use displayed_by_default <- decode.field(4, decode.optional(decode.int))
  decode.success(models.Impression(
    id:,
    language_code:,
    state:,
    order_number:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_strengths_decoder() -> decode.Decoder(
  models.GetAllDefaultStrengthsRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Strength(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_specific_strength_decoder() -> decode.Decoder(
  models.GetSpecificStrengthRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Strength(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_specific_annoyances_decoder() -> decode.Decoder(
  models.GetSpecificAnnoyancesRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Annoyance(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_annoyances_decoder() -> decode.Decoder(
  models.GetAllDefaultAnnoyancesRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Annoyance(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_show_setting_decoder() -> decode.Decoder(
  models.GetAllDefaultShowSettingRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Setting(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_user_account_id_by_email_decoder() -> decode.Decoder(
  models.GetUserAccountIdByEmailRow,
) {
  use id <- decode.field(0, decode.int)
  decode.success(models.GetUserAccountIdByEmailRow(id:))
}
