// Code generated by sqlode. DO NOT EDIT.
// engine: sqlite
// runtime: native

import db/models
import db/params
import gleam/dynamic/decode
import gleam/option.{type Option}
import sqlode/runtime

pub fn all() -> List(runtime.QueryInfo) {
  [
    runtime.QueryInfo(
      name: "GetAllGenresByLanguageCode",
      sql: "select* from genre where language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllShowFormatsByLanguageCode",
      sql: "select* from format where language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultMoodByLanguageCode",
      sql: "select* from mood where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultExpectationsByLanguageCode",
      sql: "select* from expectations where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultImpressionsByLanguageCode",
      sql: "select* from impressions where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultStrengthsByLanguageCode",
      sql: "select* from strengths where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetSpecificStrength",
      sql: "select* from strengths where name = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetSpecificAnnoyance",
      sql: "select* from annoyances where name = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultAnnoyancesByLanguageCode",
      sql: "select* from annoyances where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetAllDefaultShowSetting",
      sql: "select* from setting where displayed_by_default = true and language_code = $1;",
      command: runtime.Many,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "GetUserAccountIdByEmail",
      sql: "select id from user_account where email = $1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "AddTvShow",
      sql: "",
      command: runtime.Exec,
      param_count: 0,
    ),
  ]
}

pub fn get_all_genres_by_language_code() -> runtime.RawQuery(
  params.GetAllGenresByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllGenresByLanguageCode",
    sql: "select* from genre where language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_genres_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_show_formats_by_language_code() -> runtime.RawQuery(
  params.GetAllShowFormatsByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllShowFormatsByLanguageCode",
    sql: "select* from format where language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_show_formats_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_mood_by_language_code() -> runtime.RawQuery(
  params.GetAllDefaultMoodByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultMoodByLanguageCode",
    sql: "select* from mood where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_mood_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_expectations_by_language_code() -> runtime.RawQuery(
  params.GetAllDefaultExpectationsByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultExpectationsByLanguageCode",
    sql: "select* from expectations where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_expectations_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_impressions_by_language_code() -> runtime.RawQuery(
  params.GetAllDefaultImpressionsByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultImpressionsByLanguageCode",
    sql: "select* from impressions where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_impressions_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_strengths_by_language_code() -> runtime.RawQuery(
  params.GetAllDefaultStrengthsByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultStrengthsByLanguageCode",
    sql: "select* from strengths where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_strengths_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_specific_strength() -> runtime.RawQuery(
  params.GetSpecificStrengthParams,
) {
  runtime.RawQuery(
    name: "GetSpecificStrength",
    sql: "select* from strengths where name = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_specific_strength_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_specific_annoyance() -> runtime.RawQuery(
  params.GetSpecificAnnoyanceParams,
) {
  runtime.RawQuery(
    name: "GetSpecificAnnoyance",
    sql: "select* from annoyances where name = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_specific_annoyance_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_annoyances_by_language_code() -> runtime.RawQuery(
  params.GetAllDefaultAnnoyancesByLanguageCodeParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultAnnoyancesByLanguageCode",
    sql: "select* from annoyances where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_annoyances_by_language_code_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_all_default_show_setting() -> runtime.RawQuery(
  params.GetAllDefaultShowSettingParams,
) {
  runtime.RawQuery(
    name: "GetAllDefaultShowSetting",
    sql: "select* from setting where displayed_by_default = true and language_code = $1;",
    command: runtime.Many,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_all_default_show_setting_values,
    slice_info: fn(_) { [] },
  )
}

pub fn get_user_account_id_by_email() -> runtime.RawQuery(
  params.GetUserAccountIdByEmailParams,
) {
  runtime.RawQuery(
    name: "GetUserAccountIdByEmail",
    sql: "select id from user_account where email = $1;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_user_account_id_by_email_values,
    slice_info: fn(_) { [] },
  )
}

pub fn add_tv_show() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "AddTvShow",
    sql: "",
    command: runtime.Exec,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn prepare_get_all_genres_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_genres_by_language_code(),
    params.GetAllGenresByLanguageCodeParams(language_code: language_code),
  )
}

pub fn prepare_get_all_show_formats_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_show_formats_by_language_code(),
    params.GetAllShowFormatsByLanguageCodeParams(language_code: language_code),
  )
}

pub fn prepare_get_all_default_mood_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_mood_by_language_code(),
    params.GetAllDefaultMoodByLanguageCodeParams(language_code: language_code),
  )
}

pub fn prepare_get_all_default_expectations_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_expectations_by_language_code(),
    params.GetAllDefaultExpectationsByLanguageCodeParams(
      language_code: language_code,
    ),
  )
}

pub fn prepare_get_all_default_impressions_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_impressions_by_language_code(),
    params.GetAllDefaultImpressionsByLanguageCodeParams(
      language_code: language_code,
    ),
  )
}

pub fn prepare_get_all_default_strengths_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_strengths_by_language_code(),
    params.GetAllDefaultStrengthsByLanguageCodeParams(
      language_code: language_code,
    ),
  )
}

pub fn prepare_get_specific_strength(
  name name: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_specific_strength(),
    params.GetSpecificStrengthParams(name: name),
  )
}

pub fn prepare_get_specific_annoyance(
  name name: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_specific_annoyance(),
    params.GetSpecificAnnoyanceParams(name: name),
  )
}

pub fn prepare_get_all_default_annoyances_by_language_code(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_annoyances_by_language_code(),
    params.GetAllDefaultAnnoyancesByLanguageCodeParams(
      language_code: language_code,
    ),
  )
}

pub fn prepare_get_all_default_show_setting(
  language_code language_code: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_all_default_show_setting(),
    params.GetAllDefaultShowSettingParams(language_code: language_code),
  )
}

pub fn prepare_get_user_account_id_by_email(
  email email: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    get_user_account_id_by_email(),
    params.GetUserAccountIdByEmailParams(email: email),
  )
}

pub fn prepare_add_tv_show() -> #(String, List(runtime.Value)) {
  runtime.prepare(add_tv_show(), Nil)
}

pub fn get_all_genres_by_language_code_decoder() -> decode.Decoder(
  models.GetAllGenresByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Genre(id:, language_code:, name:, displayed_by_default:))
}

pub fn get_all_show_formats_by_language_code_decoder() -> decode.Decoder(
  models.GetAllShowFormatsByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  decode.success(models.Format(id:, language_code:, name:))
}

pub fn get_all_default_mood_by_language_code_decoder() -> decode.Decoder(
  models.GetAllDefaultMoodByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use category <- decode.field(3, decode.string)
  use displayed_by_default <- decode.field(4, decode.optional(decode.int))
  decode.success(models.Mood(
    id:,
    language_code:,
    state:,
    category:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_expectations_by_language_code_decoder() -> decode.Decoder(
  models.GetAllDefaultExpectationsByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Expectation(
    id:,
    language_code:,
    state:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_impressions_by_language_code_decoder() -> decode.Decoder(
  models.GetAllDefaultImpressionsByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  use order_number <- decode.field(3, decode.int)
  use displayed_by_default <- decode.field(4, decode.optional(decode.int))
  decode.success(models.Impression(
    id:,
    language_code:,
    state:,
    order_number:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_strengths_by_language_code_decoder() -> decode.Decoder(
  models.GetAllDefaultStrengthsByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Strength(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_specific_strength_decoder() -> decode.Decoder(
  models.GetSpecificStrengthRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Strength(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_specific_annoyance_decoder() -> decode.Decoder(
  models.GetSpecificAnnoyanceRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Annoyance(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_annoyances_by_language_code_decoder() -> decode.Decoder(
  models.GetAllDefaultAnnoyancesByLanguageCodeRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Annoyance(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_all_default_show_setting_decoder() -> decode.Decoder(
  models.GetAllDefaultShowSettingRow,
) {
  use id <- decode.field(0, decode.int)
  use language_code <- decode.field(1, decode.string)
  use name <- decode.field(2, decode.string)
  use displayed_by_default <- decode.field(3, decode.optional(decode.int))
  decode.success(models.Setting(
    id:,
    language_code:,
    name:,
    displayed_by_default:,
  ))
}

pub fn get_user_account_id_by_email_decoder() -> decode.Decoder(
  models.GetUserAccountIdByEmailRow,
) {
  use id <- decode.field(0, decode.int)
  decode.success(models.GetUserAccountIdByEmailRow(id:))
}
