// Code generated by sqlode. DO NOT EDIT.

import db/models
import db/params
import db/queries
import gleam/dynamic/decode
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import sqlight
import sqlode/runtime

fn value_to_sqlight(value: runtime.Value) -> sqlight.Value {
  case value {
    runtime.Null -> sqlight.null()
    runtime.String(v) -> sqlight.text(v)
    runtime.Int(v) -> sqlight.int(v)
    runtime.Float(v) -> sqlight.float(v)
    runtime.Bool(v) -> sqlight.bool(v)
    runtime.Bytes(v) -> sqlight.blob(v)
    runtime.Array(_) ->
      panic as "Array is not supported in the SQLite native adapter. Use raw runtime for array parameters, or ensure sqlode.slice() values are expanded before reaching value_to_sqlight."
  }
}

pub fn get_all_genres(
  db: sqlight.Connection,
) -> Result(List(models.GetAllGenresRow), sqlight.Error) {
  let q = queries.get_all_genres()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Genre(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_all_show_formats(
  db: sqlight.Connection,
) -> Result(List(models.GetAllShowFormatsRow), sqlight.Error) {
  let q = queries.get_all_show_formats()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      decode.success(models.Format(id:, language_code:, name:))
    },
  )
}

pub fn get_all_default_mood(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultMoodRow), sqlight.Error) {
  let q = queries.get_all_default_mood()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use state <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Mood(
        id:,
        language_code:,
        state:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_all_default_expectations(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultExpectationsRow), sqlight.Error) {
  let q = queries.get_all_default_expectations()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use state <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Expectation(
        id:,
        language_code:,
        state:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_all_default_impressions(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultImpressionsRow), sqlight.Error) {
  let q = queries.get_all_default_impressions()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use state <- decode.field(2, decode.string)
      use order_number <- decode.field(3, decode.int)
      use displayed_by_default <- decode.field(4, decode.optional(decode.int))
      decode.success(models.Impression(
        id:,
        language_code:,
        state:,
        order_number:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_all_default_strengths(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultStrengthsRow), sqlight.Error) {
  let q = queries.get_all_default_strengths()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Strength(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_specific_strength(
  db: sqlight.Connection,
  p: params.GetSpecificStrengthParams,
) -> Result(Option(models.GetSpecificStrengthRow), sqlight.Error) {
  let q = queries.get_specific_strength()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Strength(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
  |> result.map(fn(rows) {
    case rows {
      [row, ..] -> Some(row)
      [] -> None
    }
  })
}

pub fn get_specific_annoyances(
  db: sqlight.Connection,
  p: params.GetSpecificAnnoyancesParams,
) -> Result(Option(models.GetSpecificAnnoyancesRow), sqlight.Error) {
  let q = queries.get_specific_annoyances()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Annoyance(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
  |> result.map(fn(rows) {
    case rows {
      [row, ..] -> Some(row)
      [] -> None
    }
  })
}

pub fn get_all_default_annoyances(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultAnnoyancesRow), sqlight.Error) {
  let q = queries.get_all_default_annoyances()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Annoyance(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_all_default_show_setting(
  db: sqlight.Connection,
) -> Result(List(models.GetAllDefaultShowSettingRow), sqlight.Error) {
  let q = queries.get_all_default_show_setting()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      use language_code <- decode.field(1, decode.string)
      use name <- decode.field(2, decode.string)
      use displayed_by_default <- decode.field(3, decode.optional(decode.int))
      decode.success(models.Setting(
        id:,
        language_code:,
        name:,
        displayed_by_default:,
      ))
    },
  )
}

pub fn get_user_account_id_by_email(
  db: sqlight.Connection,
  p: params.GetUserAccountIdByEmailParams,
) -> Result(Option(models.GetUserAccountIdByEmailRow), sqlight.Error) {
  let q = queries.get_user_account_id_by_email()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.int)
      decode.success(models.GetUserAccountIdByEmailRow(id:))
    },
  )
  |> result.map(fn(rows) {
    case rows {
      [row, ..] -> Some(row)
      [] -> None
    }
  })
}

pub fn add_tv_show(db: sqlight.Connection) -> Result(Nil, sqlight.Error) {
  let q = queries.add_tv_show()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: decode.success(Nil),
  )
  |> result.map(fn(_) { Nil })
}
