micronaut:
  application:
    name: tv-show-backend
  server:
    host: ${HTTP_SERVER_HOST:0.0.0.0}
    port: ${HTTP_SERVER_PORT:8080}
    cors:
      enabled: true
      configurations:
        all:
          allowed-origins:
            - "*"

datasources:
  default:
    url: jdbc:sqlite:${DATABASE_PATH:database.db}
    driver-class-name: org.sqlite.JDBC
    maximum-pool-size: 4
    minimum-idle: 1
    connection-test-query: SELECT 1

jpa:
  default:
    entity-scan:
      packages:
        - com.shado.tv.domain
    properties:
      hibernate:
        hbm2ddl.auto: none
        show_sql: false
        dialect: org.hibernate.community.dialect.SQLiteDialect
