-- name: InitFillMoodStates: exec
INSERT INTO mood (language_code, state, displayed_by_default)
VALUES ('en', 'depressing', true),
       ('ru', 'депрессивное', true),
       ('en', 'warm', true),
       ('ru', 'теплое', true),
       ('en', 'hopeful', true),
       ('ru', 'взывающее надежду', true),
       ('en', 'bleak', true),
       ('ru', 'светлое', true),
       ('en', 'dark', true),
       ('ru', 'темное', true),
       ('en', 'cozy', true),
       ('ru', 'уютное', true),
       ('en', 'existential', true),
       ('ru', 'экзистенциальное', true),
       ('en', 'melancholic', true),
       ('ru', 'меланхоличное', true);

-- name: InitFillExpectationStates: exec
INSERT INTO expectations(language_code, state, displayed_by_default)
VALUES ('en', 'masterpiece', true),
       ('ru', 'шедевр', true),
       ('en', 'philosophical message', true),
       ('ru', 'философская мысль', true),
       ('en', 'generic', true),
       ('ru', 'посредственность', true),
       ('en', 'entertainment', true),
       ('ru', 'развлекалово', true),
       ('en', 'trash', true),
       ('ru', 'хлам', true);

-- name: InitImpressionsNames: exec
INSERT INTO impressions (language_code, order_number, state, displayed_by_default)
VALUES ('en', 10, 'masterpiece', true),
       ('ru', 10, 'шедевр', true),
       ('en', 9, 'excellent', true),
       ('ru', 9, 'восхитительно', true),
       ('en', 8, 'surprisingly good', true),
       ('ru', 8, 'удивительно годно', true),
       ('en', 6, 'average', true),
       ('ru', 6, 'средняк', true),
       ('en', 4, 'generic', true),
       ('ru', 4, 'посредственность', true),
       ('en', 1, 'terrible', true),
       ('ru', 1, 'ужас', true);

-- name: InitFillGenreNames: exec
INSERT INTO genre (language_code, name)
VALUES ('en', 'Drama'),
       ('ru', 'Драма'),
       ('en', 'Melodrama'),
       ('ru', 'Мелодрама'),
       ('en', 'Comedy'),
       ('ru', 'Комедия'),
       ('en', 'Biographical'),
       ('ru', 'Биография'),
       ('en', 'Detective'),
       ('ru', 'Детектив'),
       ('en', 'Sport'),
       ('ru', 'Спорт'),
       ('en', 'Thriller'),
       ('ru', 'Триллер'),
       ('en', 'Historical'),
       ('ru', 'Исторический'),
       ('en', 'Blockbuster'),
       ('ru', 'Блокбастер'),
       ('en', 'Animation'),
       ('ru', 'Анимация'),
       ('en', 'Fantastic'),
       ('ru', 'Фантастика'),
       ('en', 'SciFi'),
       ('ru', 'Научная фантастика'),
       ('en', 'Fantasy'),
       ('ru', 'Фэнтези'),
       ('en', 'Action'),
       ('ru', 'Экшен'),
       ('en', 'Adventure'),
       ('ru', 'Приключения'),
       ('en', 'Musical'),
       ('ru', 'Музыкаль'),
       ('en', 'Documentary'),
       ('ru', 'Документальный'),
       ('en', 'Crime'),
       ('ru', 'Криминал'),
       ('en', 'Mystery'),
       ('ru', 'Мистика'),
       ('en', 'Horror'),
       ('ru', 'Ужасы'),
       ('en', 'ShortFilm'),
       ('ru', 'Короткометражный фильм'),
       ('en', 'War'),
       ('ru', 'Военный'),
       ('en', 'ForKids'),
       ('ru', 'Для детей'),
       ('en', 'Family'),
       ('ru', 'Семейный'),
       ('en', 'Politics'),
       ('ru', 'Политика'),
       ('en', 'Western'),
       ('ru', 'Вестерн');

-- name: InitTvShowFormatNames: exec
INSERT INTO format (language_code, name)
VALUES ('en', 'Movie'),
       ('ru', 'Фильм'),
       ('en', 'TV Show'),
       ('ru', 'Телесериал'),
       ('en', 'Anime'),
       ('ru', 'Аниме'),
       ('en', 'Book'),
       ('ru', 'Книга');

-- name: InitStrengthsNames: exec
INSERT INTO strengths (language_code, name, displayed_by_default)
VALUES ('en', 'atmosphere', true),
       ('ru', 'атмосфера', true),
       ('en', 'retention', true),
       ('ru', 'Зрительское удержание', true),
       ('en', 'soundtrack', true),
       ('ru', 'музыкальное сопровождение', true),
       ('en', 'realism', true),
       ('ru', 'реалистичность', true),
       ('en', 'symbolism', true),
       ('ru', 'символизм', true),
       ('en', 'acting', true),
       ('ru', 'актерская игра', true);


-- name: InitAnnoyancesNames: exec
INSERT INTO annoyances (language_code, name, displayed_by_default)
VALUES ('en', 'plot holes', true),
       ('ru', 'дыры в сюжете', true),
       ('en', 'political propaganda', true),
       ('ru', 'политическая пропаганда', true),
       ('en', 'unrealistic dialogue', true),
       ('ru', 'неосмысленный диалог', true),
       ('en', 'plot armor', true),
       ('ru', 'сюжетная броня', true),
       ('en', 'stupid characters', true),
       ('ru', 'глупые персонажи', true),
       ('en', 'forced romance', true),
       ('ru', 'навязанная романтика', true),
       ('en', 'bad humor', true),
       ('ru', 'плохой юмор', true);

-- name: InitSettingNames: exec
INSERT INTO setting (language_code, name, displayed_by_default)
VALUES ('en', 'steampunk', true),
       ('ru', 'стим-панк', true),
       ('en', 'cyberpunk', true),
       ('ru', 'киберпанк', true),
       ('en', 'medieval', true),
       ('ru', 'средневековье', true),
       ('en', 'NASA-punk', true),
       ('ru', 'НАСА-панк', true),
       ('en', 'post-apocalyptic', true),
       ('ru', 'постапокалипсис', true),
       ('en', 'space opera', false),
       ('ru', 'космическая опера', false),
       ('en', 'ancient world', true),
       ('ru', 'древний мир', true),
       ('en', 'dystopia', true),
       ('ru', 'антиутопия', true),
       ('en', 'alternate history', false),
       ('ru', 'альтернативная история', false),
       ('en', 'magic realism', false),
       ('ru', 'магический реализм', false),
       ('en', 'western', true),
       ('ru', 'вестерн', true),
       ('en', 'lovecraftian', false),
       ('ru', 'лавкрафтовские ужасы', false),
       ('en', 'mythology', false),
       ('ru', 'мифология', false),
       ('en', 'urban fantasy', false),
       ('ru', 'городское фэнтези', false);
