import { create } from "zustand"
import type { TvShow } from "../types/types"

export const useTvShowState = create<TvShow>((set) => ({
  id: 0,
  title: "",
  year: 0,
  title_in_latin: null,
  country: null,
  setting: null,
  format_id: null,
  post_insight_id: null,
  user_account_id: null,
  extended_opinion: null,
  moral_understanding: null,
  finished: null,
  expectations_id: null,
  genres_id: null,
  mood_id: null,
  strengths_id: null,
  annoyances_id: null,
  impressions_id: null,
  visual_rate: null,
  dialogues_rate: null,
  characters_rate: null,
  story_rate: null,
  atmosphere_rate: null,
  moral_depth_rate: null,
  originality_rate: null,


  title_update:(new_title) => set({title: new_title}) ,
  year_update:(new_year) => set({year: new_year}) ,
  title_in_latin_update:(new_title_in_latin) => set({title_in_latin: new_title_in_latin}) ,
  country_update:(new_country) => set({country: new_country}) ,
  setting_update:(new_setting) => set({setting: new_setting}) ,
  format_id_update:(new_format_id) => set({format_id: new_format_id}) ,
  post_insight_id_update:(new_post_insight_id) => set({post_insight_id: new_post_insight_id}) ,
  user_account_id_update:(new_user_account_id) => set({user_account_id: new_user_account_id}) ,
  extended_opinion_update:(new_extended_opinion) => set({extended_opinion: new_extended_opinion}) ,
  moral_understanding_update:(new_moral_understanding) => set({moral_understanding: new_moral_understanding}) ,
  finished_update:(new_finished) => set({finished: new_finished}) ,
  expectations_id_update:(new_expectations_id) => set({expectations_id: new_expectations_id}) ,
  genres_id_update:(new_genres_id) => set({genres_id: new_genres_id}) ,
  mood_id_update:(new_mood_id) => set({mood_id: new_mood_id}) ,
  strengths_id_update:(new_strengths_id) => set({strengths_id: new_strengths_id}) ,
  annoyances_id_update:(new_annoyances_id) => set({annoyances_id: new_annoyances_id}) ,
  impressions_id_update:(new_impressions_id) => set({impressions_id: new_impressions_id}) ,
  visual_rate_update:(new_visual_rate) => set({visual_rate: new_visual_rate}) ,
  dialogues_rate_update:(new_dialogues_rate) => set({dialogues_rate: new_dialogues_rate}) ,
  characters_rate_update:(new_characters_rate) => set({characters_rate: new_characters_rate}) ,
  story_rate_update:(new_story_rate) => set({story_rate: new_story_rate}) ,
  atmosphere_rate_update:(new_atmosphere_rate) => set({atmosphere_rate: new_atmosphere_rate}) ,
  moral_depth_rate_update:(new_moral_depth_rate) => set({moral_depth_rate: new_moral_depth_rate}) ,
  originality_rate_update:(new_originality_rate) => set({originality_rate: new_originality_rate}) ,

}))
